// Card name to filename mapping for CBD Marseille Tarot
const CARD_MAPPING = {
  // Major Arcana (a01-a22)
  "the magician": "a01.jpg",
  "le bateleur": "a01.jpg",
  "bateleur": "a01.jpg",
  "magician": "a01.jpg",
  
  "the high priestess": "a02.jpg",
  "la papesse": "a02.jpg",
  "papesse": "a02.jpg",
  "high priestess": "a02.jpg",
  
  "the empress": "a03.jpg",
  "l'imperatrice": "a03.jpg",
  "imperatrice": "a03.jpg",
  "empress": "a03.jpg",
  
  "the emperor": "a04.jpg",
  "l'empereur": "a04.jpg",
  "empereur": "a04.jpg",
  "emperor": "a04.jpg",
  
  "the hierophant": "a05.jpg",
  "le pape": "a05.jpg",
  "pape": "a05.jpg",
  "hierophant": "a05.jpg",
  "pope": "a05.jpg",
  
  "the lovers": "a06.jpg",
  "l'amoureux": "a06.jpg",
  "amoureux": "a06.jpg",
  "lovers": "a06.jpg",
  
  "the chariot": "a07.jpg",
  "le chariot": "a07.jpg",
  "chariot": "a07.jpg",
  
  "strength": "a08.jpg",
  "la force": "a08.jpg",
  "force": "a08.jpg",
  
  "the hermit": "a09.jpg",
  "l'hermite": "a09.jpg",
  "hermit": "a09.jpg",
  
  "wheel of fortune": "a10.jpg",
  "la roue de fortune": "a10.jpg",
  "roue de fortune": "a10.jpg",
  "wheel": "a10.jpg",
  
  "justice": "a11.jpg",
  "la justice": "a11.jpg",
  
  "the hanged man": "a12.jpg",
  "le pendu": "a12.jpg",
  "pendu": "a12.jpg",
  "hanged man": "a12.jpg",
  
  "death": "a13.jpg",
  "la mort": "a13.jpg",
  "mort": "a13.jpg",
  
  "temperance": "a14.jpg",
  "la temperance": "a14.jpg",
  
  "the devil": "a15.jpg",
  "le diable": "a15.jpg",
  "diable": "a15.jpg",
  "devil": "a15.jpg",
  
  "the tower": "a16.jpg",
  "la maison dieu": "a16.jpg",
  "maison dieu": "a16.jpg",
  "tower": "a16.jpg",
  
  "the star": "a17.jpg",
  "l'etoile": "a17.jpg",
  "etoile": "a17.jpg",
  "star": "a17.jpg",
  
  "the moon": "a18.jpg",
  "la lune": "a18.jpg",
  "lune": "a18.jpg",
  "moon": "a18.jpg",
  
  "the sun": "a19.jpg",
  "le soleil": "a19.jpg",
  "soleil": "a19.jpg",
  "sun": "a19.jpg",
  
  "judgement": "a20.jpg",
  "le jugement": "a20.jpg",
  "jugement": "a20.jpg",
  "judgment": "a20.jpg",
  
  "the world": "a21.jpg",
  "le monde": "a21.jpg",
  "monde": "a21.jpg",
  "world": "a21.jpg",
  
  "the fool": "a22.jpg",
  "le mat": "a22.jpg",
  "le fou": "a22.jpg",
  "mat": "a22.jpg",
  "fool": "a22.jpg",
  
  // Wands/Rods (b01-b14)
  "ace of wands": "b01.jpg",
  "ace of rods": "b01.jpg",
  "one of wands": "b01.jpg",
  "two of wands": "b02.jpg",
  "two of rods": "b02.jpg",
  "three of wands": "b03.jpg",
  "three of rods": "b03.jpg",
  "four of wands": "b04.jpg",
  "four of rods": "b04.jpg",
  "five of wands": "b05.jpg",
  "five of rods": "b05.jpg",
  "six of wands": "b06.jpg",
  "six of rods": "b06.jpg",
  "seven of wands": "b07.jpg",
  "seven of rods": "b07.jpg",
  "eight of wands": "b08.jpg",
  "eight of rods": "b08.jpg",
  "nine of wands": "b09.jpg",
  "nine of rods": "b09.jpg",
  "ten of wands": "b10.jpg",
  "ten of rods": "b10.jpg",
  "page of wands": "b11.jpg",
  "page of rods": "b11.jpg",
  "valet of wands": "b11.jpg",
  "knight of wands": "b12.jpg",
  "knight of rods": "b12.jpg",
  "cavalier of wands": "b12.jpg",
  "queen of wands": "b13.jpg",
  "queen of rods": "b13.jpg",
  "king of wands": "b14.jpg",
  "king of rods": "b14.jpg",
  
  // Cups (c01-c14)
  "ace of cups": "c01.jpg",
  "one of cups": "c01.jpg",
  "two of cups": "c02.jpg",
  "three of cups": "c03.jpg",
  "four of cups": "c04.jpg",
  "five of cups": "c05.jpg",
  "six of cups": "c06.jpg",
  "seven of cups": "c07.jpg",
  "eight of cups": "c08.jpg",
  "nine of cups": "c09.jpg",
  "ten of cups": "c10.jpg",
  "page of cups": "c11.jpg",
  "valet of cups": "c11.jpg",
  "knight of cups": "c12.jpg",
  "cavalier of cups": "c12.jpg",
  "queen of cups": "c13.jpg",
  "king of cups": "c14.jpg",
  
  // Pentacles/Coins (d01-d14)
  "ace of pentacles": "d01.jpg",
  "ace of coins": "d01.jpg",
  "one of pentacles": "d01.jpg",
  "two of pentacles": "d02.jpg",
  "two of coins": "d02.jpg",
  "three of pentacles": "d03.jpg",
  "three of coins": "d03.jpg",
  "four of pentacles": "d04.jpg",
  "four of coins": "d04.jpg",
  "five of pentacles": "d05.jpg",
  "five of coins": "d05.jpg",
  "six of pentacles": "d06.jpg",
  "six of coins": "d06.jpg",
  "seven of pentacles": "d07.jpg",
  "seven of coins": "d07.jpg",
  "eight of pentacles": "d08.jpg",
  "eight of coins": "d08.jpg",
  "nine of pentacles": "d09.jpg",
  "nine of coins": "d09.jpg",
  "ten of pentacles": "d10.jpg",
  "ten of coins": "d10.jpg",
  "page of pentacles": "d11.jpg",
  "page of coins": "d11.jpg",
  "valet of pentacles": "d11.jpg",
  "knight of pentacles": "d12.jpg",
  "knight of coins": "d12.jpg",
  "cavalier of pentacles": "d12.jpg",
  "queen of pentacles": "d13.jpg",
  "queen of coins": "d13.jpg",
  "king of pentacles": "d14.jpg",
  "king of coins": "d14.jpg",
  
  // Swords (e01-e14)
  "ace of swords": "e01.jpg",
  "one of swords": "e01.jpg",
  "two of swords": "e02.jpg",
  "three of swords": "e03.jpg",
  "four of swords": "e04.jpg",
  "five of swords": "e05.jpg",
  "six of swords": "e06.jpg",
  "seven of swords": "e07.jpg",
  "eight of swords": "e08.jpg",
  "nine of swords": "e09.jpg",
  "ten of swords": "e10.jpg",
  "page of swords": "e11.jpg",
  "valet of swords": "e11.jpg",
  "knight of swords": "e12.jpg",
  "cavalier of swords": "e12.jpg",
  "queen of swords": "e13.jpg",
  "king of swords": "e14.jpg"
};

// Export for use in main script
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CARD_MAPPING;
}
